"""removed extraneous foreign keys

Revision ID: 44fb3098b561
Revises: 67ef4ddd4ee8
Create Date: 2023-10-17 16:56:09.976054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fb3098b561'
down_revision = '67ef4ddd4ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blockeds', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_blockeds_blockee_id_blockees', type_='foreignkey')
        batch_op.drop_constraint('fk_user_blockeds_blocker_id_blockers', type_='foreignkey')
        batch_op.drop_column('blocker_id')
        batch_op.drop_column('blockee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_blockeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blockee_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('blocker_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_blockeds_blocker_id_blockers', 'blockers', ['blocker_id'], ['id'])
        batch_op.create_foreign_key('fk_user_blockeds_blockee_id_blockees', 'blockees', ['blockee_id'], ['id'])

    # ### end Alembic commands ###
