"""removed some nullable constraints

Revision ID: c5a2d1e4f21e
Revises: a708e6939eea
Create Date: 2023-10-19 10:28:50.395227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a2d1e4f21e'
down_revision = 'a708e6939eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
